# Generated by Django 4.2.21 on 2025-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
